### ISSUE TITLE
The parent theme is missing

### ISSUE THREAD

**Issue by alansjourney** [raamdev/independent-publisher-child-theme#1]
After installing the child theme, it reports as a broken theme:

_"The following themes are installed but incomplete. Themes must have a stylesheet and a template._

_Independent Publisher Child Theme - The parent theme is missing. Please install the "independent-publisher" parent theme."_

**Comment by raamdev** [comment]
Did you install [the parent theme](https://github.com/raamdev/independent-publisher-child-theme) first?

**Comment by alansjourney** [comment]
Yes

I get the same error if the parent theme is Activated or not.

**Comment by raamdev** [comment]
The problem was that you were downloading the developer zip file from here on GitHub, which named the folder `independent-publisher-master`. It should be `independent-publisher`, otherwise the Child Theme cannot find it.

We fixed this together on IRC, so I'm closing this issue.
